### ISSUE TITLE
Confusion about Pro beta version "Allow Charging" option when sleeping.

### ISSUE THREAD

**Issue by mikebore** [davidwernhart/AlDente#255]
My interpretation by just looking at the settings, is that with the slider in the **left** default position charging is **not** allowed and I would have to turn it ON by moving to the **right** position to allow. I would have to turn the setting ON by moving it to the right to allow charging.

However looking at the dropdown message that appears when hovering it seems to be the opposite?

<img width="586" alt="Screenshot 2021-04-20 at 16 18 32" src="https://user-images.githubusercontent.com/79205106/115424928-0ce10680-a1f7-11eb-908f-ffc8be6f0f26.png">

Also I don't understand why the statement says that with charging inhibited you may overshoot desired percentage? Doesn't "Charging inhibited" mean no charging so how will it overshoot?

Does anybody else find this confusing?

**Comment by MatthiasKerbl** [comment]
Hi @mikebore,

this is a little bit confusing right now and we already fixed it in our final version.
For now, the text next to the slider is the current state.

AlDente can not control the charging of your MacBook when your MacBook is asleep. Therefore, the MacBook will keep the charging state it had before going to sleep. When your MacBook is currently charging to your desired limit and your MacBook is going into sleep, it will overshoot your limit and charge to 100% since AlDente is not active while your MacBook is in sleep.

Hope that helps.

**Comment by mikebore** [comment]
Thanks very much for clarifying.
