### ISSUE TITLE
Mojave Support

### ISSUE THREAD

**Issue by yabo-boye** [davidwernhart/AlDente#305]
Is there any way this can be supported on Mojave, even with limited functionality? I upgraded to Catalina just for this, unfortunately the OS has a few very annoying problems that are killing my workflow (especially Bluetooth issues). I would love some version of this to work in Mojave, and I would contribute to make it happen.

Thank you for your amazing work!

**Comment by MatthiasKerbl** [comment]
Hi @yabo-boye ,
I have just included an answer to your question in our README:
"Due to SwiftUI not being compatible with older versions of macOS, AlDente is only compatible with macOS 11 Big Sur. Even though it might be possible to get AlDente to work on older MacBooks and macOS versions too, we are currently not working on it."
