### ISSUE TITLE
Pro version gets automatically updated to Aldente Free 1.04, losing pro features

### ISSUE THREAD

**Issue by zhouyifan0904** [davidwernhart/AlDente#308]

**Comment by davidwernhart** [comment]
Hi,

the issue seems to come since we've changed the app name from AlDente-Pro to AlDente with this update.
Paddle, our payment provider, stores the license file based on the app name on your computer. 

Please enter the key you got from the purchase email under "Activate License" in General Settings.

Unfortunately, there is not much I can do about this problem. But on the bright side, your license is stored permanently again after you enter it once for the update.

Sorry for the inconveniences,
David
