### ISSUE TITLE
Unable to use latest release on 10.15.7

### ISSUE THREAD

**Issue by ssabetan** [davidwernhart/AlDente#396]
Hey all,

First time user here. I'm getting the following error when launching for the first time:

<img width="532" alt="error" src="https://user-images.githubusercontent.com/2876713/135700843-a934d906-c685-4e3e-9c0a-1a2351886a10.png">

I am on a MacBook Pro (Retina, 13-inch, Late 2013) and am aware of the charging limitation.

**Comment by MatthiasKerbl** [comment]
Hi @ssabetan,

Due to the limitations of SwiftUI AlDente is only compatible with macOS 11.0 or newer. You either have to update your MacBook to macOS 11 or you can download AlDente Classic 2.2 which is an older version of AlDente but it doesn't work as well as the newer versions of AlDente.
You can download AlDente Classic 2.2 here: https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias
