### ISSUE TITLE
Clamshell discharge doesn't work reliably 

### ISSUE THREAD

**Issue by Logoct** [davidwernhart/AlDente#422]
The clamshell discharge feature mostly doesn't work when the laptop is already closed and instead returns to paused charging and sail mode when attempting to enable it. Workarounds are restarting the MacBook and then enabling clamshell discharge or opening the MacBook enabling discharge then closing the MacBook to clamshell mode and reenabling it.

AlDente Pro 1.08 
macOS Monterey 12.0.1

**Comment by Jseeca** [comment]
I'm assuming you are talking about M1? 
Originally clamshell mode had no support with discharge with the M1. I remember It was stated by the author and its on the git front front page. This was due to technical limitations. A several months later (today) I updated the AlDente and found that the clamshell mode discharge works surprisingly! 

It is however as you said buggy, for me it does indeed discharge when it's in the mode but getting the mode to turn on is a hit or miss, half the time it ends up putting the Mac to sleep and you have to wake the device up and try again, until it just works lol. Your works arounds mentioned do also work too. 

Strangely the discharge feature is still listed as not compatible with clamshell mode on the git page. But when you click the link for an explanation, there is no explanation on the following link. Maybe they forgot to update it? Or technically speaking the discharge clamshell still isn't fully supported?

**Comment by Logoct** [comment]
Yep I'm on a M1 MacBook Pro and since AlDente 1.07 I've been able to clamshell discharge but only if I follow my workarounds and have the same issue with it going to sleep half the time. Hopefully it gets fixed at some point because it's pretty unstable now and sometimes just returns to paused charging after a while.

**Comment by MrCaturdayNight** [comment]
I'm seeing this on AlDente 1.09 Pro and macOS Monterey 12.0.1 on a MacBook Pro w/ M1Pro. The work around mentioned above worked for me but most of the time clicking the discharge button while in clamshell just causes my monitor to shutdown and kicks me back to the login screen.

**Comment by MatthiasKerbl** [comment]
Hi everyone,

We have just released a new version of AlDente (1.10). https://github.com/davidwernhart/AlDente/releases
This version should fix the issues you have experienced with AlDente.

If you still experience any problems with AlDente, feel free to let us know.

Thank you for your patience!

Cheers,
Matthias
