### ISSUE TITLE
MacOS Big Sur Compatibility

### ISSUE THREAD

**Issue by abshake96** [davidwernhart/AlDente#44]
Hi,

First of all, thanks for this great tool! Just wanted to know if this tool will continue working in the Big Sur update?

If not, do you have plans to make an update? More than happy to help you test as per your convenience.

Additionally, if you're not planning to make the update, is there some kind of guidance you can offer as to the step we'd require to take. 

Thanks again!

**Comment by diogoterremoto** [comment]
I've just upgraded from Catalina to Big Sur and AlDente seems to be working. 

<img width="415" alt="AlDente menu bar open" src="https://user-images.githubusercontent.com/21290402/99060374-dc39d880-2597-11eb-9116-b66362e03745.png">

<img width="305" alt="'Battery not charging' at 80% on menu bar" src="https://user-images.githubusercontent.com/21290402/99060383-de039c00-2597-11eb-92b2-a529078ff0ca.png">

**Comment by davidwernhart** [comment]
I also just updated to big sur today, like @diogoterremoto it seems to work without any problems for me right now. Sadly, I cannot guarantee anything, but the outlook is good. I suppose that the underlying functionality of AlDente (SMC Key manipulating) will not stop to work even with future OSX versions. That being said, this method most likely will not work anymore on the new ARM Macs.

**Comment by JGeek00** [comment]
I have a MacBook Pro 15 2019 with Big Sur and I confirm that it's working fine. Thanks to the developer for this app, this option should be native on macOS. I had my MacBook Pro 3 months connected to the charger because it was connected to two external monitors, and in that situation the battery drains so fast. After that 3 month, the battery is not working as it should be, it is jumping numbers on the percentage, and with the same use it has between one hour and one hour and a half less autonomy. So, again, thanks to the developer for this application.

**Comment by togiberlin** [comment]
I can confirm. 
Works on my MB Pro 13" Early 2015 /w OS X Big Sur flawlessly.

**Comment by hfsken** [comment]
Works fine on MacBook Pro (Retina, 13-inch, Late 2013) with macOS BigSur 11.0.1 (20B29)

**Comment by brandonloong** [comment]
Working on my 2019 MacBook Pro 16" with Big Sur 11.0.1! Love this app, not sure why Apple can't just include this default like EVs do.

**Comment by n-thumann** [comment]
Works on my MacBook Pro (15", 2018) running macOS 11.0.1 :v:

**Comment by abshake96** [comment]
I've upgraded as well. Seems to be working great for me! Closing this issue now!
