### ISSUE TITLE
Any solution for older macs than the ones supported?

### ISSUE THREAD

**Issue by andreschouhy** [davidwernhart/AlDente#458]
Hi, I have a macbook pro 13 from 2009, MacOS 10.11 El Capitan. I understand that AlDente doesn't support my computer. But is there some workaround for my case? Maybe some terminal command I can automate?
Thank you

**Comment by andreschouhy** [comment]
By the way, I'm only interested in the Charge Limiter feature.

**Comment by MatthiasKerbl** [comment]
Hi @andreschouhy,

The current version of AlDente (1.12) is only compatible with macOS 11 Big Sur. This means it is compatible with all MacBooks since 2013.
AlDente Classic 2.2 is Compatible with macOS 10.15 Catalina. This means it is compatible with all MacBooks since 2012.
AlDente Classic 1.2 might be compatible with older versions of macOS. However, I am not sure. You can download it here: https://github.com/davidwernhart/AlDente/releases?page=2

Cheers,
Matthias
