### ISSUE TITLE
[Bug] Battery percentage changes in Discharge mode

### ISSUE THREAD

**Issue by huang-1331** [davidwernhart/AlDente#459]
When I activate / deactivate Discharge mode, my battery percentage changes.
<img width="518" alt="스크린샷 2021-11-16 오후 12 02 26" src="https://user-images.githubusercontent.com/21101314/141928501-434a6f63-9b71-4baf-ab0a-dc6557f9a36b.png">
<img width="523" alt="스크린샷 2021-11-16 오후 12 02 51" src="https://user-images.githubusercontent.com/21101314/141928519-8975f721-c043-4c4e-8281-7e1478f49c21.png">

**Comment by MatthiasKerbl** [comment]
Hi @huang-1331,

This happens on my MacBook sometimes too and has nothing to do with AlDente since Discharge does nothing else than internally unplugging your MacBook. Therefore, if you would really unplug your MacBook, you would experience the same thing. I am not 100% sure why this happens sometimes but my guess is that the SoC readout changes a little bit when a MacBook gets unplugged but it is nothing to worry about.

Cheers,
Matthias
