### ISSUE TITLE
aldente free,app recognized as aldente pro,and cant change Disable Sleep until Charge Limit 

### ISSUE THREAD

**Issue by avichou** [davidwernhart/AlDente#495]
**Describe the bug**
i am a free user but in terminal etc,i get recoginzed as pro

more importantly,if i use discharge mode,to let the battery drain,the option to put mac to sleep in apple menu is grayed out ,and since im not a pro user i cannot change that 

**Expected behavior**
as a non pro,i should have the option to Disable Sleep until Charge Limit set off by default

**Screenshots**
![image](https://user-images.githubusercontent.com/86660671/145584094-14801809-ea21-4025-9ca3-4bc82f18c76c.png)

**MacBook (please complete the following information):**
 - mbp 14 8c
 - macOS 12.1
 - free but looks pro?? wtf
 - 1.10
 - eveyrhing default

**Comment by MatthiasKerbl** [comment]
Hi @avichou,

Since the Discharge feature seemed to be more stable when sleep was deactivated, we enabled "Disable Sleep until Charge Limit" even in the AlDente Free for this certain scenario. However, the Discharge feature is stable enough now and we will disable "Disable Sleep until Charge Limit" in the Free version with the next update again.

AlDente Free and AlDente Pro are the same apps but when you do not have AlDente Pro activated, you do not have access to all the Pro features.

Cheers,
Matthias
