### ISSUE TITLE
Sailing mode doesn't seem to work

### ISSUE THREAD

**Issue by elgs** [davidwernhart/AlDente#502]
**Describe the bug**
1. I set charge limit to 60% and sailing mode difference to 20%;
2. I discharged the battery to the charge limit 60%; 
3. When discharge stopped, the current battery level is 60%;
4. I use an app called coconutBattery to monitor current charge/discharge watts and current charge mAh;
5. The charge/discharge watts stays at 0 watt, which is good;
6. However, the current charge mAh goes up and down around the charge limit within the range of 50mAh, which I expect it to go down slowly but monotonically;
7. It looks like the micro cycles;
8. This happened on both of my MBPs described below;

**MacBook (please complete the following information):**
 - MacBook model 
 MacBook Pro (15-inch, 2017) and MacBook Pro (16-inch, 2021) M1 Max
 - macOS version
 macOS Monterey 12.1

 - AlDente Pro or AlDente Free?
 AlDente Pro
 - AlDente Version?
 1.10

 - List of all enabled/disabled settings in AlDente:
 Enabled:
 Sailing mode
 Stop charging when sleeping

**Comment by MatthiasKerbl** [comment]
Hi @elgs,

Thank you for the precise description.
The Sailing Mode should work just fine since you noticed yourself that the charging wattage stays at zero. My guess, why the current charge mAh goes up and down a bit is because of the margin of error of the SoC. The SoC is not really a precise number and always fluctuates.
You can find more details about the Sailing Mode on our blog: https://apphousekitchen.com/feature-explanation-sailing-mode/

Cheers,
Matthias
