### ISSUE TITLE
*HELP* I have miss entered my email address while purchasing the pro version

### ISSUE THREAD

**Issue by HRamadan1** [davidwernhart/AlDente#545]
I have written my email address with one letter misspelled and now I can't reach my (already paid subscription ) and can't reach support because support is only for pro members !!!
what should I do :( 
@MatthiasKerbl

**Comment by york601** [comment]
I left my email and paid but didn't receive the letter what even clicked "restore your authorization code" @MatthiasKerbl

**Comment by MatthiasKerbl** [comment]
> I have written my email address with one letter misspelled and now I can't reach my (already paid subscription ) and can't reach support because support is only for pro members !!! what should I do :( @MatthiasKerbl

Hi @HRamadan1,

No worries, just send me the email you used to purchase AlDente Pro to news@apphousekitchen.com

Cheers,
Matthias

**Comment by HRamadan1** [comment]
@MatthiasKerbl  Thank you so much 
may you kindly check the email 🙏

**Comment by york601** [comment]
&nbsp; ***@***.***.That was the email, while I used to purchase AlDente Pro.
&nbsp; Looking forward to your reply.



发自我的iPhone

------------------ Original ------------------
From: Matthias Kerbl ***@***.***&gt;
Date: 周日,1月 16,2022 23:58
To: davidwernhart/AlDente ***@***.***&gt;
Cc: york601 ***@***.***&gt;, Comment ***@***.***&gt;
Subject: Re: [davidwernhart/AlDente] *HELP* I have miss entered my email address while purchasing the pro version (Issue #545)





  
I have written my email address with one letter misspelled and now I can't reach my (already paid subscription ) and can't reach support because support is only for pro members !!! what should I do :( @MatthiasKerbl
  
Hi @HRamadan1,
 
No worries, just send me the email you used to purchase AlDente Pro to ***@***.***
 
Cheers,
 Matthias
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by MatthiasKerbl** [comment]
Hi @HRamadan1 and @york601,

I have forwarded the payment emails to the correct email addresses now.

Cheers,
Matthias
