### ISSUE TITLE
Discharge and Charge Limit Not Working on M1 Pro MBP 16

### ISSUE THREAD

**Issue by 15boyyu** [davidwernhart/AlDente#579]
MacOS 12.1
MacBook Pro 16 M1 Pro
AlDente 1.14 Free

I have issue with both the charge limiter and discharge.

Charge Limiter seems to do nothing. 

When I click on the discharge button, the power source changes to battery for about 1 second, then it shifts to power adapter, after a short period, it ignores AlDente and starts to charge. 

So despite enabled discharge, it keeps cycling through the three states as the images show below, and the battery state of charge keeps going up.
![IMG_4464](https://user-images.githubusercontent.com/98908400/152212962-313aa3f9-d367-4829-b0b5-2c2065c0bb61.jpg)
![IMG_4463](https://user-images.githubusercontent.com/98908400/152212965-a19b4c3a-c958-471c-8084-295263d20ac6.jpg)
![IMG_4462](https://user-images.githubusercontent.com/98908400/152212967-62a22f95-cb4c-446e-b756-98bdd9c4dd9f.jpg)

**Comment by lord-lucario** [comment]
I have the same problem and am seeking an answer in #577

**Comment by peterfan727** [comment]
I have the same spec machine, and the Free version works perfectly fine for mine. I suggest reinstalling the Helper under General Settings and then restart your Mac.

**Comment by MatthiasKerbl** [comment]
Hi @15boyyu,

Do you have Optimized battery charging in System Preferences disabled?
Did you try a complete reinstall of AlDente?

Cheers,
Matthias

**Comment by quitemadmax** [comment]
Thanks for the quick reply.
I installed the recently released version 1.33.2 and it works fine.

I'm working on translating the app into Turkmen language to get a discount on the Pro version (once I read a post about it on your website).

I really like your app! I should have started using it earlier (before its health dropped to 89%), but whenever I started, it was just the right time. 
I recommend your app to all Mac users I know.

I've also just added the link to an update on [another forum](https://forums.macrumors.com/threads/al-dente-not-working.2432008/post-33964501) I found. 
Since the problem is new, it hasn't shown up almost anywhere yet, perhaps another wanderer will find my post and will fix the problem.
