### ISSUE TITLE
App kill battery ? (in my case, i'm not the first)

### ISSUE THREAD

**Issue by batterykiller** [davidwernhart/AlDente#604]
**Describe the bug**
A clear and concise description of what the bug is.>

I use free app during 3 days
 <img alt="Screenshot 2022-02-12 at 22 10 19" width="563" src="https://user-images.githubusercontent.com/99562265/153728968-0b760d77-d65f-4d91-be3b-275b4d01eca6.png">
 
In only 2 days ! Mac M1 - 10 months battery - 25 cycles
 
How can i regain capacity battery ??? Since I uninstalled the app I have already done 2 cycles and nothing change :(
 
 I turned off the mac, unplugged it for 1 minute then turned it back on, nothing happened. I installed this app to save my battery as the mac did not limit it to 80% despite the option. I see it failed!
 
pls help

**Comment by m4rkw** [comment]
I'm not affiliated with the author but please document exactly how you used the app, what settings and for how long?

**Comment by m4rkw** [comment]
I struggle to see how AlDente could possibly be damaging a battery with the way it works. I think it's far more likely that it's just throwing Apple's battery capacity algorithm off, possibly due to the charge level being only taken up to ~50% and then back down again repeatedly. Perhaps the charge level itself is less accurate at 50% than it is at 100% and so this adds to the inaccuracy because it might think it has 50% charge but really only has 45%. If this theory is true then repeated full cycles up to 100% should eventually fix the calibration but it may take more than a couple depending on how the algorithm works. Remember Apple have no way to determine the actual mAh capacity of the battery, they can only see the charge level in voltage, how much charge the battery takes in while charging and then monitor (approximately) how much energy is used as it discharges.

**Comment by m4rkw** [comment]
Apple's algorithm is designed with the expectation that the normal cycle of the battery will be 0% -> 80%/100% -> discharge, if this is fundamentally changed such that 50% is the limit it's easy to see how the calculation could be completely thrown off. What will be interesting to see is if this eventually recalibrates given enough "normal" data to work with. /cc @joujek

**Comment by joujek** [comment]
I was in touch with Apple support engineer - he mentioned :
 "Apple power management is quite complicated and you should not believe any third-party apps with battery health/capacity reports- eg Coconut. In other hand disabling Apple Optimisation and using third-party apps can have negative impact on battery and warranty. Only valuable report is the one in system preferences -> battery".
In other hand my iStats menu shows capacity in range 86-90%, where System Preferences reports 92%.
I have extended my warranty with apple care protection plan and will see....

My Pro is connected with dock almost all the time. Sometimes I unplug for some time during weekends. During last 2moths I observed one situation where whole week (Mo-Fri) macOS automatically discharge battery to 80% and pause charging with information: Rarely used on battery. Then I disconnected for weekend work, and since next 2 weeks i have 100% charged battery again. I guess that OS is trying to learn my routines... but I know that learning is more efficiency when used on battery more often (like iPhones).

The good news is that Apple engineer said " The 90% capacity is still great - just use your PRO normally and don't take care about "raw numbers" "

**Comment by m4rkw** [comment]
Yeah tbh I tried this app out briefly and decided that it's best to just leave it alone. The M1 gets such good battery life that its just never going to be a problem to me, and the mental cost of worrying about the battery far exceeds the monetary cost of having them replace the battery in 3-4 years. far more likely ill sell the machine long before it needs a battery anyway.

**Comment by MatthiasKerbl** [comment]
> **Describe the bug** A clear and concise description of what the bug is.>
> 
> I use free app during 3 days <img alt="Screenshot 2022-02-12 at 22 10 19" width="563" src="https://user-images.githubusercontent.com/99562265/153728968-0b760d77-d65f-4d91-be3b-275b4d01eca6.png">
> 
> In only 2 days ! Mac M1 - 10 months battery - 25 cycles
> 
> How can i regain capacity battery ??? Since I uninstalled the app I have already done 2 cycles and nothing change :(
> 
> I turned off the mac, unplugged it for 1 minute then turned it back on, nothing happened. I installed this app to save my battery as the mac did not limit it to 80% despite the option. I see it failed!
> 
> pls help

Hi @batterykiller,

As @m4rkw already explained, it is most likely only a calibration issue or an inaccuracy in the battery capacity readout of macOS. However, 2% of capacity fluctuation is completely neglectable in my opinion. On my personal MacBook for example, which is 5 and a half years old and has 450+ cycles, the battery capacity sometimes fluctuates up to 15% depending on usage and calibration status.

If you want to keep your battery as healthy as possible for as long as possible, I would recommend using AlDente to limit charging when used while plugged in and do full charge cycles (100%-0%-100%) every week or so. Don't interpret too much in the battery capacity number in the short term it is more of an indication of how the battery capacity might develop over the long term but only if the battery is well calibrated.

Hope that helps.

Cheers,
Matthias
