### ISSUE TITLE
下载第一次使用，关不了放电模式，充不进电了

### ISSUE THREAD

**Issue by zmz125** [davidwernhart/AlDente#614]
第一次使用，在菜单栏打开了放电模式，结果到20%以内还不能充电，现在马上关机了，卸了软件依然充不进电！！！急！！！

**Comment by MatthiasKerbl** [comment]
Hi @zmz125,

Please answer the following questions:

**Describe the bug**
A clear and concise description of what the bug is.

**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots or screen recordings to help explain your problem.

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608)
 - macOS version (https://support.apple.com/en-us/HT201260)
 - AlDente Pro or AlDente Free?
 - AlDente Version?
 - List of all enabled/disabled settings in AlDente:

**Additional context**
Add any other context about the problem here.
