### ISSUE TITLE
Unable to use pro version on new MacBook pro. 

### ISSUE THREAD

**Issue by f0rever-johnson** [davidwernhart/AlDente#619]
Got a new MacBook Pro M1 Pro.  I had AlDente installed on my old macbook that  has since been wiped and traded in. How to I transfer that license over to a new MacBook? When I try to use the key, I get a license has already been used error.

**Comment by MatthiasKerbl** [comment]
Hi @f0rever-johnson,

Usually, you need to deactivate the old license on the old MacBook in order to use it on the new one. However, you can also write our support your license code and we will handle it in the backend. You can find our support email address in your payment confirmation email of AlDente Pro.

Cheers,
Matthias
