### ISSUE TITLE
Charges Over Limit

### ISSUE THREAD

**Issue by michaelmyc** [davidwernhart/AlDente#649]
**Describe the bug**
I'm observing that the battery sometimes charges significantly over the limit. I often see my Macbook charge 1% to 3% over the limit, and it might be the same reason? But sometimes (although fairly rarely) I see Al Dente charging 15% over the limit. It's not charging to full overnight so Al Dente is definitely still functional to some extent. 

**To Reproduce**
Charge the laptop. I had the lid closed when charging. And I think I plugged in the charger after I closed my lid (not super sure)? 

**Expected behavior**
The laptop stops charging at the limit (70% for me).

**Screenshots**
MacOS battery settings and proof of over-charging:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15188392/162361258-dd09afb1-f6b4-495b-a2d4-a64cfdf6711e.png">

Limiter settings:
<img width="472" alt="image" src="https://user-images.githubusercontent.com/15188392/162361322-82c7a186-bb87-439c-9cb8-1ef7fa8c88a2.png">

Charge history:
<img width="780" alt="image" src="https://user-images.githubusercontent.com/15188392/162361357-0a2d70c6-a860-4e62-ba84-2acc4d1651a9.png">

**MacBook (please complete the following information):**
 - MacBook model (https://support.apple.com/en-us/HT201608) MacBook Pro (14-inch, 2021)
 - macOS version (https://support.apple.com/en-us/HT201260) Monterey 12.3.1
 - AlDente Pro or AlDente Free? Free
 - AlDente Version? 1.15.2
 - List of all enabled/disabled settings in AlDente: N/A

**Additional context**
N/A

**Comment by MatthiasKerbl** [comment]
Hi @michaelmyc,

The 1-3% overcharging is within the margin of error and is most likely caused by fluctuations in the macOS battery percentage.

Regarding the overcharging of 15% sometimes, this is due to AlDente Free not being able to control charging when your MacBook is in sleep. With AlDente Pro, we introduced more features (Stop Charging When Sleeping, Disable Sleep until Charge Limit) to control Charging and sleep better. If you are interested, you can check it out here: https://apphousekitchen.com/

Cheers,
Matthias
