### ISSUE TITLE
Ver. 1.17 Pro doesn't launch when offline

### ISSUE THREAD

**Issue by CBDAN** [davidwernhart/AlDente#679]
**Describe the bug**
AlDente 1.17 Pro doesn't launch when the Mac is offline, because the app needs to establish a connection with paddleapi.com.

**Comment by DamonHD** [comment]
This also seem likely to be what blocks logging in for 30s or more, since I usually will not have a working WiFi session running when I open up my MBA.  It is intensely annoying since one of the nice features of macOS has traditionally been that it's very quick to resume.  Please fix: defer licence checking until later.

**Comment by MatthiasKerbl** [comment]
Hi @CBDAN and @DamonHD,

We could fix this issue and have just released a new version AlDente 1.17.1.
https://github.com/davidwernhart/AlDente/releases/tag/1.17.1

Cheers,
Matthias

**Comment by DamonHD** [comment]
Thank you.  I have installed 1.17.1 and I'll see how it works for me!

Rgds

Damon

**Comment by DamonHD** [comment]
Doesn't seem to have made a difference for me.  Last few MBA openings at least 8s delay to flashing password prompt.  Without AlDente running, no delay.

Rgds

Damon

**Comment by MatthiasKerbl** [comment]
> Doesn't seem to have made a difference for me. Last few MBA openings at least 8s delay to flashing password prompt. Without AlDente running, no delay.
> 
> Rgds
> 
> Damon

Hi @DamonHD,

your issue does not seem to be correlated to this issue.
Could you open a new GitHub issue with a precise description of what exactly happens in which scenario?

Thanks,
Matthias
