### ISSUE TITLE
AlDente not working - battery at 100%

### ISSUE THREAD

**Issue by pkowal-x** [davidwernhart/AlDente#686]
**Describe the bug**
AlDente set up for different values, like 88 or 92%, but battery always charged to 100%.
This is a second time I file the bug, this time on another machine. This makes me wonder if the software works at all.
<img width="344" alt="Screen Shot 2022-05-21 at 08 47 49" src="https://user-images.githubusercontent.com/102844818/169639681-0c842553-9c16-4bcf-a180-a6528da981b5.png">
<img width="472" alt="Screen Shot 2022-05-21 at 08 47 43" src="https://user-images.githubusercontent.com/102844818/169639704-311bf877-b182-4239-bb98-b11ab60a2f98.png">

**MacBook (please complete the following information):**
M1 MacBook Air
MacOs 12.3.1
AlDente Free, but this way it will never be Pro

**Comment by MatthiasKerbl** [comment]
Hi @pkowal-x,

I am sorry you are having trouble with AlDente.
There are multiple reasons why the Charge Limiter might not work for you.

Do you have Apple's "Optimized Battery Charging" disabled?
Did you do a macOS update recently?
Are you aware that the Charge Limiter in AlDente Free does not work when your MacBook is in sleep or powered off?
Did you try a complete reinstall of AlDente?
Did you try to turn off your MacBook, close the lid, unplug it, wait for 5 minutes, and turn it on again?
Could you send us a debug file to get more details about your issue?

Cheers,
Matthias

**Comment by ovq** [comment]
I see this too, at least since 12.4. 
My MBP is set to 70% (sail 10%), but it always stays on 100% with AD running. I have restarted multiple times, now I just tried the 5' shutdown/unplug suggestion from above. Let's see.

**Comment by enovikoff** [comment]
It is not clear to me that “launch at login” means that Al Dente doesn’t remain running after logout (or lock.)  Other apps solve the problem of remaining available while the MBP is on (with periods of sleep) so why can’t Al Dente do it?  The conflicting information in this thread also makes it unclear whether Al Dente works when the MBP is asleep, or if this behavior depends on whether one uses the free or paid version.  In my experience when I hit the Touch ID/lock button while my MacBook is attached to the charger or dock, it successfully prevents a full charge and the MBP seems to be sleeping. The most recent problem occurred when I used the MBP on battery and closed the lid when I was done, then plugged it in later and observed that it was charging towards 100% after I used Touch ID to unlock it and start using it, with “launch at login” off.   Turning that setting on might have prevented this problem, but I still am puzzled why it’s necessary, since other system utility apps just resume without issue.

**Comment by MatthiasKerbl** [comment]
Hi @pkowal-x,

Do you still experience this issue with our newest version AlDente 1.18?
https://github.com/davidwernhart/AlDente/releases

Cheers,
Matthias

**Comment by pkowal-x** [comment]
> Hi @pkowal-x,
> 
> Do you still experience this issue with our newest version AlDente 1.18? https://github.com/davidwernhart/AlDente/releases
> 
> Cheers, Matthias

I confirm, that the issue is resolved.

**Comment by maps10** [comment]
> Hi [@pkowal-x](https://github.com/pkowal-x),
> 
> I am sorry you are having trouble with AlDente. There are multiple reasons why the Charge Limiter might not work for you.
> 
> Do you have Apple's "Optimized Battery Charging" disabled? Did you do a macOS update recently? Are you aware that the Charge Limiter in AlDente Free does not work when your MacBook is in sleep or powered off? Did you try a complete reinstall of AlDente? Did you try to turn off your MacBook, close the lid, unplug it, wait for 5 minutes, and turn it on again? Could you send us a debug file to get more details about your issue?
> 
> Cheers, Matthias

I am on MacBook Air m2 and I tried the free version of the ardent and it doesn't work
