### ISSUE TITLE
Charging watch from MBP

### ISSUE THREAD

**Issue by tomwolsky** [davidwernhart/AlDente#695]
My watch seems to have become slow in charging from my MBP, especially the final top up, 97% and up. It was over an hour on 98%. I'm wondering if the watch is seeing the MBP as not on power, so is doing a trickle charge. As soon as I switched AlDente to Top Up the watch run through the last few percent. 

Has anyone else seen this behavior before? It seems new to me. 

Thanks very much.

**Comment by Bachsau** [comment]
I do not believe this is possible, since the watch charger does not establish a data connection. I just uses the USB port as a power source. The watch has it's own charging controller, which might have decided to stop charging for another reason, like heat or optimized charging. Charging also slows down signifcantly for the last 20% to reduce battery strain.

**Comment by tomwolsky** [comment]
Thank you very much. That's very helpful. The slow down at the end seems to have become more pronounced.

**Comment by MatthiasKerbl** [comment]
Hi @tomwolsky,

I don't think either that AlDente can influence the watch of your MacBook at all.

Did you still experience any correlation between using the AlDente and the watch? Otherwise, I would close this issue.

Cheers,
Matthias

**Comment by tomwolsky** [comment]
Hi Mathias,The problem hasn’t persisted and can be closed. I suspect it might have been an OS build I was using at the time. Thank you. All the best,TomOn Sep 1, 2022, at 08:23, Matthias Kerbl ***@***.***> wrote:﻿
Hi @tomwolsky,
I don't think either that AlDente can influence the watch of your MacBook at all.
Did you still experience any correlation between using the AlDente and the watch? Otherwise, I would close this issue.
Cheers,
Matthias
