### ISSUE TITLE
Heat protection doesn't apply when Top Up has been selected

### ISSUE THREAD

**Issue by johnnynomad** [davidwernhart/AlDente#738]
**Describe the bug**
When I select Top Up, the battery keeps charging even though the Max. temp I have set under 'Heat Protection' has been exceeded.

**To Reproduce**
1. Set Max. temp and enable Heat Protection
2. Select "Top Up"

**Expected behavior**
The Max. temp set under 'Heat Protection' should apply under all circumstances.

**MacBook (please complete the following information):**
 - MacBook model: MacBook Pro (14-inch, 2021)
 - macOS version: 12.4
 - AlDente Pro or AlDente Free?: Pro
 - AlDente Version: 1.17.1

**Comment by MatthiasKerbl** [comment]
Hi @johnnynomad,

This behavior is actually intended. Due to Top Up most of the time being used in a hurry before you leave for a day of use without the plug, we do not want Heat Protection to slow down the charging process.
If you want to charge to 100% with Heat Protection still being enabled, just use the slider to set the Charge Limit to 100%.

Cheers,
Matthias
