### ISSUE TITLE
Could you hide the icon in the dock? 

### ISSUE THREAD

**Issue by martianmartian** [davidwernhart/AlDente#801]
hi there, 

thanks for this life saving app. 

just a little request. Could you hide the icon in the dock?  because this is a background app, it makes sense to save some docking room by removing the icon while the app is running.

**Comment by MatthiasKerbl** [comment]
Hi @martianmartian,

Due to some people having trouble finding AlDente, we implemented the dock icon and have it activated automatically after installation. However, since most people don’t want to use the dock icon in the long term, we also included a setting to hide it. Just into settings in AlDente -> Appearance -> Other -> and disable Show Dock Icon.

Cheers,
Matthias

**Comment by GIT-Preserved** [comment]
Thank you so much, I think it's the fact that Appearance -> Other -> disable Show Dock Icon happens to be perfectly hidden in the settings under the default window size of AlDente that led me here 😂
