### ISSUE TITLE
Date of last calibration + reminder

### ISSUE THREAD

**Issue by shimo-web** [davidwernhart/AlDente#808]
I think for people like me (who have a MacBook on a cable practically all the time) this ability to check when I last did a calibration and preferably a reminder every 2 weeks would be helpful.

**Comment by MatthiasKerbl** [comment]
Hi @shimo-web,

That's a good idea, thank you for sharing.
Since we already have feature requests for this open here #575 and #572 and #676, I will close this issue. But feel free to add your thoughts as well.
I will write updates about these feature requests in the issues mentioned.

Cheers,
Matthias
